# Generated by Django 3.0.5 on 2020-04-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalcase', models.IntegerField()),
                ('activecase', models.IntegerField()),
                ('newcase', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('newdeath', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('tests', models.IntegerField()),
            ],
        ),
    ]
