# Generated by Django 3.0.5 on 2020-04-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.TextField(default='India'),
            preserve_default=False,
        ),
    ]
