# Generated by Django 3.0.5 on 2020-04-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.AlterField(
            model_name='data',
            name='totalcase',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
