# Generated by Django 3.0.5 on 2020-04-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'about'},
        ),
    ]
