# Generated by Django 3.0.5 on 2020-04-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20200423_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
    ]
