# Generated by Django 3.0.5 on 2020-04-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20200423_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='totalcase',
            field=models.IntegerField(),
        ),
    ]
