# Generated by Django 3.0.5 on 2020-04-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_auto_20200423_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='CountryData',
        ),
    ]
