# Generated by Django 3.0.5 on 2020-04-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_auto_20200423_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydata',
            name='flag',
            field=models.TextField(null=True),
        ),
    ]
