# Generated by Django 3.0.5 on 2020-04-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_countrydata_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='heading',
            field=models.CharField(max_length=100),
        ),
    ]
