# Generated by Django 3.0.5 on 2020-04-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_auto_20200426_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydata',
            name='flag',
            field=models.ImageField(upload_to=''),
        ),
    ]
