# Generated by Django 3.0.5 on 2020-04-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0011_countrydata_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('link', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'CountryNews',
            },
        ),
    ]
