# Generated by Django 3.0.5 on 2020-04-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0012_countrynews'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrynews',
            name='date',
            field=models.DateField(default='2020-04-12'),
            preserve_default=False,
        ),
    ]
