# Generated by Django 3.0.5 on 2020-04-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0013_countrynews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrynews',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
