# Generated by Django 3.0.5 on 2020-04-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0014_auto_20200430_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrynews',
            name='date',
            field=models.DateField(),
        ),
    ]
