# Generated by Django 3.0.5 on 2020-05-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0015_auto_20200430_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('country', models.TextField(primary_key=True, serialize=False)),
                ('totalcase', models.IntegerField()),
                ('newcase', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('newdeath', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
