# Generated by Django 3.0.5 on 2020-05-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0015_auto_20200430_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField()),
                ('totalcase', models.IntegerField()),
                ('newcase', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('newdeath', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
