# Generated by Django 3.0.5 on 2020-05-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0016_dailydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyData',
        ),
    ]
